<div class="edgtf-slider">
                     <div class="edgtf-slider-inner">
                        <link href="css/css(1)" rel="stylesheet" property="stylesheet" type="text/css" media="all">
                        <div id="rev_slider_1_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-source="gallery" style="margin: 0px auto; background: rgb(38, 38, 38); padding: 0px; height: 600px; overflow: visible;">
                           <div id="rev_slider_1_1" class="rev_slider fullwidthabanner revslider-initialised tp-simpleresponsive rev_redraw_on_blurfocus" style="margin-top: 0px; margin-bottom: 0px; height: 600px;" data-version="5.4.8" data-slideactive="rs-3">
                              <ul class="tp-revslider-mainul" style="visibility: visible; display: block; overflow: hidden; width: 1425px; height: 100%; max-height: none; left: 0px;">
                                 <li data-index="rs-1" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="" data-delay="5000" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli" style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0; background-color: rgba(255, 255, 255, 0);">
                                    <div class="slotholder" style="position: absolute; top: 0px; left: 0px; z-index: 0; width: 100%; height: 100%; visibility: inherit; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0);">
                                       <!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png" alt="a" title="h1-slide-1" width="1920" height="1010" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg defaultimg" data-no-retina="">-->
                                       <div class="tp-bgimg defaultimg " data-bgcolor="undefined" style="background-repeat: no-repeat; background-image: url(&quot;https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; z-index: 20;" src="https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png"></div>
                                    </div>
                                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: hidden; left: -247px; top: -115px; z-index: 5;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-1-layer-15" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;0&#39;,&#39;0&#39;,&#39;0&#39;,&#39;0&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;90&#39;,&#39;90&#39;,&#39;90&#39;,&#39;90&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-1.jpg" alt="a" data-ww="[&#39;1920px&#39;,&#39;1920px&#39;,&#39;1920px&#39;,&#39;1920px&#39;]" data-hh="[&#39;1010px&#39;,&#39;1010px&#39;,&#39;1010px&#39;,&#39;1010px&#39;]" width="1920" height="1010" data-no-retina="" style="width: 1920px; height: 1010px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap  tp-hidden-caption" style="position: absolute; display: block; visibility: hidden; left: 350px; top: 17px; z-index: 6;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-1-layer-16" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;350&#39;,&#39;350&#39;,&#39;350&#39;,&#39;350&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;17&#39;,&#39;17&#39;,&#39;17&#39;,&#39;17&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;off&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1200,&quot;speed&quot;:800,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:bottom;rZ:90deg;sX:2;sY:2;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-1-img-1.png" alt="" data-ww="[&#39;522px&#39;,&#39;522px&#39;,&#39;522px&#39;,&#39;522px&#39;]" data-hh="[&#39;560px&#39;,&#39;560px&#39;,&#39;560px&#39;,&#39;560px&#39;]" width="522" height="560" data-no-retina="" style="height: 560px; width: 522px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap  tp-hidden-caption" style="position: absolute; display: block; visibility: hidden; left: 322px; top: 232px; z-index: 7;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: hidden; transform: matrix(1, 0, 0, 1, 0, 0);">
                                             <div class="tp-caption   tp-resizeme" id="slide-1-layer-17" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;322&#39;,&#39;322&#39;,&#39;322&#39;,&#39;322&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;232&#39;,&#39;232&#39;,&#39;232&#39;,&#39;232&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;off&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1950,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[100%];y:0px;z:0px;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0px;skY:0;opacity:1;&quot;,&quot;mask&quot;:&quot;x:[-100%];y:0;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-1-img-3.png" alt="a" data-ww="[&#39;360px&#39;,&#39;360px&#39;,&#39;360px&#39;,&#39;360px&#39;]" data-hh="[&#39;62px&#39;,&#39;62px&#39;,&#39;62px&#39;,&#39;62px&#39;]" width="360" height="62" data-no-retina="" style="height: 62px; width: 360px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap  tp-hidden-caption" style="position: absolute; display: block; visibility: hidden; left: 1px; top: 198px; z-index: 8;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: hidden; transform: matrix(1, 0, 0, 1, 0, 0);">
                                             <div class="tp-caption   tp-resizeme" id="slide-1-layer-10" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;0&#39;,&#39;0&#39;,&#39;-35&#39;,&#39;-9&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;374&#39;,&#39;198&#39;,&#39;250&#39;,&#39;170&#39;]" data-fontsize="[&#39;40&#39;,&#39;40&#39;,&#39;35&#39;,&#39;25&#39;]" data-lineheight="[&#39;102&#39;,&#39;102&#39;,&#39;85&#39;,&#39;60&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;on&#39;,&#39;off&#39;]" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1900,&quot;speed&quot;:1300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:[100%];s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; white-space: nowrap; font-size: 40px; line-height: 102px; font-weight: 400; color: rgb(255, 255, 255); letter-spacing: 0px; font-family: Sacramento; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; border-width: 0px; margin: 0px; padding: 0px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">or select a category below to find the best places </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap  tp-hidden-caption" style="position: absolute; display: block; visibility: hidden; left: 308px; top: 188px; z-index: 9;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-1-layer-11" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;308&#39;,&#39;308&#39;,&#39;243&#39;,&#39;209&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;374&#39;,&#39;188&#39;,&#39;250&#39;,&#39;170&#39;]" data-lineheight="[&#39;22&#39;,&#39;22&#39;,&#39;22&#39;,&#39;22&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;on&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2600,&quot;speed&quot;:900,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:bottom;z:0px;rX:0deg;rZ:-100deg;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-1-img-2.png" alt="a" data-ww="[&#39;51px&#39;,&#39;51px&#39;,&#39;45px&#39;,&#39;30px&#39;]" data-hh="[&#39;40px&#39;,&#39;40px&#39;,&#39;35px&#39;,&#39;24px&#39;]" width="51" height="40" data-no-retina="" style="height: 40px; width: 51px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                 </li>
                                 <li data-index="rs-2" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="" data-delay="5000" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli" style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0; background-color: rgba(255, 255, 255, 0);">
                                    <div class="slotholder" style="position: absolute; top: 0px; left: 0px; z-index: 0; width: 100%; height: 100%; visibility: inherit; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0);">
                                       <!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png" alt="a" title="h1-slide-1" width="1920" height="1010" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg defaultimg" data-no-retina="">-->
                                       <div class="tp-bgimg defaultimg " data-bgcolor="undefined" style="background-repeat: no-repeat; background-image: url(&quot;https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; z-index: 20;" src="https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png"></div>
                                    </div>
                                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: hidden; left: -247px; top: -115px; z-index: 5;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-2-layer-15" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;0&#39;,&#39;0&#39;,&#39;0&#39;,&#39;0&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;90&#39;,&#39;90&#39;,&#39;90&#39;,&#39;90&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-2.jpg" alt="a" data-ww="[&#39;1920px&#39;,&#39;1920px&#39;,&#39;1920px&#39;,&#39;1920px&#39;]" data-hh="[&#39;1010px&#39;,&#39;1010px&#39;,&#39;1010px&#39;,&#39;1010px&#39;]" width="1920" height="1010" data-no-retina="" style="width: 1920px; height: 1010px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap  tp-hidden-caption" style="position: absolute; display: block; visibility: hidden; left: 350px; top: 17px; z-index: 6;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-2-layer-16" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;350&#39;,&#39;350&#39;,&#39;350&#39;,&#39;350&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;17&#39;,&#39;17&#39;,&#39;17&#39;,&#39;17&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;off&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:300,&quot;speed&quot;:800,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:bottom;rZ:90deg;sX:2;sY:2;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-2-img-1.png" alt="a" data-ww="[&#39;522px&#39;,&#39;522px&#39;,&#39;522px&#39;,&#39;522px&#39;]" data-hh="[&#39;560px&#39;,&#39;560px&#39;,&#39;560px&#39;,&#39;560px&#39;]" width="523" height="560" data-no-retina="" style="height: 560px; width: 522px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap  tp-hidden-caption" style="position: absolute; display: block; visibility: hidden; left: 322px; top: 232px; z-index: 7;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: hidden; transform: matrix(1, 0, 0, 1, 0, 0);">
                                             <div class="tp-caption   tp-resizeme" id="slide-2-layer-17" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;322&#39;,&#39;322&#39;,&#39;322&#39;,&#39;322&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;232&#39;,&#39;232&#39;,&#39;232&#39;,&#39;232&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;off&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1100,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[100%];y:0px;z:0px;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0px;skY:0;opacity:1;&quot;,&quot;mask&quot;:&quot;x:[-100%];y:0;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-1-img-3.png" alt="a" data-ww="[&#39;360px&#39;,&#39;360px&#39;,&#39;360px&#39;,&#39;360px&#39;]" data-hh="[&#39;62px&#39;,&#39;62px&#39;,&#39;62px&#39;,&#39;62px&#39;]" width="360" height="62" data-no-retina="" style="height: 62px; width: 360px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: hidden; left: 433px; top: 623px; z-index: 8;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-2-layer-19" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;0&#39;,&#39;0&#39;,&#39;-35&#39;,&#39;-35&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;374&#39;,&#39;374&#39;,&#39;250&#39;,&#39;250&#39;]" data-fontsize="[&#39;40&#39;,&#39;40&#39;,&#39;35&#39;,&#39;35&#39;]" data-lineheight="[&#39;102&#39;,&#39;102&#39;,&#39;85&#39;,&#39;85&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;on&#39;,&#39;on&#39;,&#39;off&#39;]" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; white-space: nowrap; font-size: 40px; line-height: 102px; font-weight: 400; color: rgb(255, 255, 255); letter-spacing: 0px; font-family: Sacramento; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; border-width: 0px; margin: 0px; padding: 0px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">or select a category below to find the best places </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: hidden; left: 995px; top: 654px; z-index: 9;">
                                       <div class="tp-loop-wrap rs-pendulum" style="position: absolute; display: block; min-height: 40px; min-width: 51px; transform: matrix3d(0.998342, -0.057564, 0, 0, 0.057564, 0.998342, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-2-layer-20" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;308&#39;,&#39;308&#39;,&#39;243&#39;,&#39;243&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;374&#39;,&#39;374&#39;,&#39;250&#39;,&#39;250&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 0.0001; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">
                                                <img src="images/h1-slide-1-img-2.png" alt="a" data-ww="[&#39;51px&#39;,&#39;51px&#39;,&#39;45&#39;,&#39;45&#39;]" data-hh="[&#39;40px&#39;,&#39;40px&#39;,&#39;35px&#39;,&#39;35px&#39;]" width="51" height="40" data-no-retina="" style="width: 51px; height: 40px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> 
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </li>
                                 <li data-index="rs-3" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="" data-delay="5000" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 20; visibility: inherit; opacity: 1; background-color: rgba(255, 255, 255, 0);">
                                    <div class="slotholder" style="position: absolute; top: 0px; left: 0px; z-index: 0; width: 100%; height: 100%; visibility: inherit; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0);">
                                       <!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png" alt="a" title="h1-slide-1" width="1920" height="1010" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg defaultimg" data-no-retina="">-->
                                       <div class="tp-bgimg defaultimg " data-bgcolor="undefined" style="background-repeat: no-repeat; background-image: url(&quot;https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; z-index: 20;" src="https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png"></div>
                                    </div>
                                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: -247px; top: -195px; z-index: 5;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-3-layer-15" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;0&#39;,&#39;0&#39;,&#39;0&#39;,&#39;0&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;10&#39;,&#39;10&#39;,&#39;90&#39;,&#39;90&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-3.jpg" alt="a" data-ww="[&#39;1920px&#39;,&#39;1920px&#39;,&#39;1920px&#39;,&#39;1920px&#39;]" data-hh="[&#39;1010px&#39;,&#39;1010px&#39;,&#39;1010px&#39;,&#39;1010px&#39;]" width="1920" height="1010" data-no-retina="" style="width: 1920px; height: 1010px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap  tp-hidden-caption" style="position: absolute; display: block; visibility: visible; left: 348px; top: 21px; z-index: 6;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-3-layer-16" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;348&#39;,&#39;348&#39;,&#39;350&#39;,&#39;350&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;21&#39;,&#39;21&#39;,&#39;17&#39;,&#39;17&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;off&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:300,&quot;speed&quot;:800,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:bottom;rZ:90deg;sX:2;sY:2;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-3-img-1.png" alt="a" data-ww="[&#39;522px&#39;,&#39;522px&#39;,&#39;522px&#39;,&#39;522px&#39;]" data-hh="[&#39;560px&#39;,&#39;560px&#39;,&#39;560px&#39;,&#39;560px&#39;]" width="523" height="560" data-no-retina="" style="height: 560px; width: 522px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap  tp-hidden-caption" style="position: absolute; display: block; visibility: visible; left: 322px; top: 232px; z-index: 7;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: hidden; transform: matrix(1, 0, 0, 1, 0, 0);">
                                             <div class="tp-caption   tp-resizeme" id="slide-3-layer-17" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;322&#39;,&#39;322&#39;,&#39;322&#39;,&#39;322&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;232&#39;,&#39;232&#39;,&#39;232&#39;,&#39;232&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;off&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1100,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[100%];y:0px;z:0px;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0px;skY:0;opacity:1;&quot;,&quot;mask&quot;:&quot;x:[-100%];y:0;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"><img src="images/h1-slide-1-img-3.png" alt="a" data-ww="[&#39;360px&#39;,&#39;360px&#39;,&#39;360px&#39;,&#39;360px&#39;]" data-hh="[&#39;62px&#39;,&#39;62px&#39;,&#39;62px&#39;,&#39;62px&#39;]" width="360" height="62" data-no-retina="" style="height: 62px; width: 360px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 433px; top: 623px; z-index: 8;">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-3-layer-19" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;0&#39;,&#39;0&#39;,&#39;-35&#39;,&#39;-35&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;374&#39;,&#39;374&#39;,&#39;250&#39;,&#39;250&#39;]" data-fontsize="[&#39;40&#39;,&#39;40&#39;,&#39;35&#39;,&#39;35&#39;]" data-lineheight="[&#39;102&#39;,&#39;102&#39;,&#39;85&#39;,&#39;85&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;on&#39;,&#39;on&#39;,&#39;off&#39;]" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; white-space: nowrap; font-size: 40px; line-height: 102px; font-weight: 400; color: rgb(255, 255, 255); letter-spacing: 0px; font-family: Sacramento; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; border-width: 0px; margin: 0px; padding: 0px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">or select a category below to find the best places </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 995px; top: 654px; z-index: 9;">
                                       <div class="tp-loop-wrap rs-pendulum" style="position: absolute; display: block; min-height: 40px; min-width: 51px; transform: matrix3d(0.966376, 0.257133, 0, 0, -0.257133, 0.966376, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">
                                          <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                             <div class="tp-caption   tp-resizeme" id="slide-3-layer-20" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;308&#39;,&#39;308&#39;,&#39;243&#39;,&#39;243&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;374&#39;,&#39;374&#39;,&#39;250&#39;,&#39;250&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">
                                                <img src="images/h1-slide-1-img-2.png" alt="a" data-ww="[&#39;51px&#39;,&#39;51px&#39;,&#39;45&#39;,&#39;45&#39;]" data-hh="[&#39;40px&#39;,&#39;40px&#39;,&#39;35px&#39;,&#39;35px&#39;]" width="51" height="40" data-no-retina="" style="width: 51px; height: 40px; transition: none 0s ease 0s; text-align: inherit; line-height: 0px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 14px;"> 
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </li>
                                 <li data-index="rs-4" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="" data-delay="5000" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli" style="width: 100%; height: 100%; overflow: hidden;">
                                    <div class="slotholder" style="position:absolute; top:0px; left:0px; z-index:0;width:100%;height:100%;">
                                       <!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png" alt="a" title="h1-slide-1" width="1920" height="1010" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg defaultimg" data-no-retina="">-->
                                       <div class="tp-bgimg defaultimg " data-bgcolor="undefined" style="background-repeat: no-repeat; background-image: url(&quot;https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 0;" src="https://urbango.qodeinteractive.com/wp-content/plugins/revslider/admin/assets/images/transparent.png"></div>
                                    </div>
                                    <div class="tp-parallax-wrap " style=" position:absolute;display:block;;visibility:hidden">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position:absolute;display:block;;">
                                             <div class="tp-caption   tp-resizeme" id="slide-4-layer-15" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;0&#39;,&#39;0&#39;,&#39;0&#39;,&#39;0&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;40&#39;,&#39;40&#39;,&#39;90&#39;,&#39;90&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; visibility: hidden;"><img src="images/h1-slide-4.jpg" alt="a" data-ww="[&#39;1920px&#39;,&#39;1920px&#39;,&#39;1920px&#39;,&#39;1920px&#39;]" data-hh="[&#39;1010px&#39;,&#39;1010px&#39;,&#39;1010px&#39;,&#39;1010px&#39;]" width="1920" height="1010" data-no-retina=""> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap " style=" position:absolute;display:block;;visibility:hidden">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position:absolute;display:block;;">
                                             <div class="tp-caption   tp-resizeme" id="slide-4-layer-16" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;350&#39;,&#39;350&#39;,&#39;350&#39;,&#39;350&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;17&#39;,&#39;17&#39;,&#39;17&#39;,&#39;17&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;off&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:300,&quot;speed&quot;:800,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:bottom;rZ:90deg;sX:2;sY:2;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; visibility: hidden;"><img src="images/h1-slide-4-img-1.png" alt="a" data-ww="[&#39;522px&#39;,&#39;522px&#39;,&#39;522px&#39;,&#39;522px&#39;]" data-hh="[&#39;560px&#39;,&#39;560px&#39;,&#39;560px&#39;,&#39;560px&#39;]" width="523" height="560" data-no-retina=""> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap " style=" position:absolute;display:block;;visibility:hidden">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position:absolute;display:block;;">
                                             <div class="tp-caption   tp-resizeme" id="slide-4-layer-17" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;322&#39;,&#39;322&#39;,&#39;322&#39;,&#39;322&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;232&#39;,&#39;232&#39;,&#39;232&#39;,&#39;232&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;off&#39;,&#39;off&#39;,&#39;off&#39;]" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1100,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[100%];y:0px;z:0px;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0px;skY:0;opacity:1;&quot;,&quot;mask&quot;:&quot;x:[-100%];y:0;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; visibility: hidden;"><img src="images/h1-slide-1-img-3.png" alt="a" data-ww="[&#39;360px&#39;,&#39;360px&#39;,&#39;360px&#39;,&#39;360px&#39;]" data-hh="[&#39;62px&#39;,&#39;62px&#39;,&#39;62px&#39;,&#39;62px&#39;]" width="360" height="62" data-no-retina=""> </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap " style=" position:absolute;display:block;;visibility:hidden">
                                       <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position:absolute;display:block;;">
                                             <div class="tp-caption   tp-resizeme" id="slide-4-layer-19" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;0&#39;,&#39;0&#39;,&#39;-35&#39;,&#39;-35&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;374&#39;,&#39;374&#39;,&#39;250&#39;,&#39;250&#39;]" data-fontsize="[&#39;40&#39;,&#39;40&#39;,&#39;35&#39;,&#39;35&#39;]" data-lineheight="[&#39;102&#39;,&#39;102&#39;,&#39;85&#39;,&#39;85&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="[&#39;on&#39;,&#39;on&#39;,&#39;on&#39;,&#39;off&#39;]" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; white-space: nowrap; font-size: 40px; line-height: 102px; font-weight: 400; color: rgb(255, 255, 255); letter-spacing: 0px; font-family: Sacramento; visibility: hidden;">or select a category below to find the best places </div>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="tp-parallax-wrap " style=" position:absolute;display:block;;visibility:hidden">
                                       <div class="tp-loop-wrap rs-pendulum" style="position:absolute;display:block;;">
                                          <div class="tp-mask-wrap" style="position:absolute;display:block;;">
                                             <div class="tp-caption   tp-resizeme" id="slide-4-layer-20" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;308&#39;,&#39;308&#39;,&#39;243&#39;,&#39;243&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;374&#39;,&#39;374&#39;,&#39;250&#39;,&#39;250&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; visibility: hidden;">
                                                <img src="images/h1-slide-1-img-2.png" alt="a" data-ww="[&#39;51px&#39;,&#39;51px&#39;,&#39;45&#39;,&#39;45&#39;]" data-hh="[&#39;40px&#39;,&#39;40px&#39;,&#39;35px&#39;,&#39;35px&#39;]" width="51" height="40" data-no-retina=""> 
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </li>
                              </ul>
                              <div style="left: 0px;" class="tp-static-layers">
                                 <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 163px; top: 407px; z-index: 25;">
                                    <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                       <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                          <div class="tp-caption   tp-static-layer" id="slider-1-layer-21" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;-365&#39;,&#39;-265&#39;,&#39;-15&#39;,&#39;0&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;186&#39;,&#39;136&#39;,&#39;159&#39;,&#39;104&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-responsive="off" data-startslide="0" data-endslide="3" data-frames="[{&quot;delay&quot;:650,&quot;speed&quot;:1200,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 25; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: rgb(255, 255, 255); letter-spacing: 0px; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; border-width: 0px; margin: 0px; padding: 0px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">
                                             <div class="wpb_widgetised_column wpb_content_element">
                                                <div class="wpb_wrapper">
                                                   <div class="widget edgtf-search-post-type-widget">
                                                      <form role="search" method="get" class="edgtf-search-post-type" action="https://urbango.qodeinteractive.com/">
                                                         <label class="screen-reader-text">Search for:</label>
                                                         <div class="edgtf-search-post-type-inner">
                                                            <div class="edgtf-post-type-search-field">
                                                               <input type="search" placeholder="What are you looking for?" value="" name="s" title="Search for:" required>
                                                            </div>
                                                            <div class="edgtf-post-type-search-submit">
                                                               <button type="submit">
                                                               <i class="edgtf-icon-font-awesome fas fa-search "></i> <span class="edgtf-post-type-search-label">Search</span>
                                                               </button>
                                                            </div>
                                                            <input type="hidden" name="post_type" value="listing-item">
                                                            <input type="hidden" name="edgtf-listing-search" value="yes">
                                                         </div>
                                                      </form>
                                                   </div>
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 163px; top: 101px; z-index: 26;">
                                    <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                       <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                          <div class="tp-caption   tp-resizeme tp-static-layer" id="slider-1-layer-23" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;-570&#39;,&#39;-483&#39;,&#39;-244&#39;,&#39;-9&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;-139&#39;,&#39;-154&#39;,&#39;-114&#39;,&#39;-156&#39;]" data-fontsize="[&#39;36&#39;,&#39;30&#39;,&#39;25&#39;,&#39;22&#39;]" data-lineheight="[&#39;102&#39;,&#39;90&#39;,&#39;80&#39;,&#39;55&#39;]" data-width="none" data-height="[&#39;107&#39;,&#39;none&#39;,&#39;none&#39;,&#39;none&#39;]" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-startslide="0" data-endslide="3" data-frames="[{&quot;delay&quot;:250,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[,2,2,2]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[,2,2,2]" style="z-index: 26; max-width: none; white-space: nowrap; font-size: 30px; line-height: 90px; font-weight: 500; color: rgb(255, 255, 255); letter-spacing: 0px; font-family: &quot;Shorelines Script&quot;; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; border-width: 0px; margin: 0px; padding: 0px 2px; min-height: 0px; min-width: 0px; max-height: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">explore </div>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 158px; top: 176px; z-index: 27;">
                                    <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                       <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                          <div class="tp-caption   tp-resizeme tp-static-layer" id="slider-1-layer-24" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;-314&#39;,&#39;-212&#39;,&#39;38&#39;,&#39;-9&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;30&#39;,&#39;19&#39;,&#39;63&#39;,&#39;-64&#39;]" data-fontsize="[&#39;90&#39;,&#39;70&#39;,&#39;60&#39;,&#39;45&#39;]" data-lineheight="[&#39;95&#39;,&#39;75&#39;,&#39;65&#39;,&#39;50&#39;]" data-width="[&#39;686&#39;,&#39;686&#39;,&#39;686&#39;,&#39;260&#39;]" data-height="[&#39;286&#39;,&#39;286&#39;,&#39;286&#39;,&#39;none&#39;]" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-startslide="0" data-endslide="3" data-frames="[{&quot;delay&quot;:350,&quot;speed&quot;:1100,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;center&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 27; min-width: 686px; max-width: 686px; white-space: normal; font-size: 70px; line-height: 75px; font-weight: 600; color: rgb(255, 255, 255); letter-spacing: 0px; font-family: Montserrat; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; border-width: 0px; margin: 0px; padding: 0px; min-height: 286px; max-height: 286px; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">Discover the Best Spots </div>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 162px; top: 348px; z-index: 28;">
                                    <div class="tp-loop-wrap" style="position:absolute;display:block;;">
                                       <div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;">
                                          <div class="tp-caption   tp-resizeme tp-static-layer" id="slider-1-layer-25" data-x="[&#39;center&#39;,&#39;center&#39;,&#39;center&#39;,&#39;center&#39;]" data-hoffset="[&#39;-440&#39;,&#39;-358&#39;,&#39;-127&#39;,&#39;-2&#39;]" data-y="[&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;,&#39;middle&#39;]" data-voffset="[&#39;110&#39;,&#39;61&#39;,&#39;85&#39;,&#39;208&#39;]" data-fontsize="[&#39;22&#39;,&#39;20&#39;,&#39;18&#39;,&#39;16&#39;]" data-lineheight="[&#39;30&#39;,&#39;25&#39;,&#39;23&#39;,&#39;22&#39;]" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-startslide="0" data-endslide="3" data-frames="[{&quot;delay&quot;:500,&quot;speed&quot;:1150,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="[&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;,&#39;inherit&#39;]" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 28; white-space: nowrap; font-size: 20px; line-height: 25px; font-weight: 500; color: rgb(255, 255, 255); letter-spacing: 0px; font-family: Montserrat; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; border-width: 0px; margin: 0px; padding: 0px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">Find the best places by clicking below </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                              <script>var htmlDiv = document.getElementById("rs-plugin-settings-inline-css"); var htmlDivCss="";
                                 if(htmlDiv) {
                                 	htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss;
                                 }else{
                                 	var htmlDiv = document.createElement("div");
                                 	htmlDiv.innerHTML = "<style>" + htmlDivCss + "</style>";
                                 	document.getElementsByTagName("head")[0].appendChild(htmlDiv.childNodes[0]);
                                 }
                              </script>
                              <div class="tp-bannertimer tp-bottom" style="visibility: hidden; width: 35.44%; transform: translate3d(0px, 0px, 0px);"></div>
                              <div class="tp-loader spinner4" style="display: none;">
                                 <div class="dot1"></div>
                                 <div class="dot2"></div>
                                 <div class="bounce1"></div>
                                 <div class="bounce2"></div>
                                 <div class="bounce3"></div>
                              </div>
                              <div class="tp-leftarrow tparrows urbango-navigation" style="top: 50%; transform: matrix(1, 0, 0, 1, 20, 14); left: 0px;"><span class="edgtf-nav-arrow"></span></div>
                              <div class="tp-rightarrow tparrows urbango-navigation" style="top: 50%; transform: matrix(1, 0, 0, 1, -60, 14); left: 100%;"><span class="edgtf-nav-arrow"></span></div>
                           </div>
                           <script>var htmlDiv = document.getElementById("rs-plugin-settings-inline-css"); var htmlDivCss="";
                              if(htmlDiv) {
                              	htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss;
                              }else{
                              	var htmlDiv = document.createElement("div");
                              	htmlDiv.innerHTML = "<style>" + htmlDivCss + "</style>";
                              	document.getElementsByTagName("head")[0].appendChild(htmlDiv.childNodes[0]);
                              }
                           </script>
                           <script type="text/javascript">
                              if (setREVStartSize!==undefined) setREVStartSize(
                              	{c: '#rev_slider_1_1', responsiveLevels: [1920,1602,1025,480], gridwidth: [1300,1100,600,300], gridheight: [955,600,700,625], sliderLayout: 'auto'});
                              			
                              var revapi1,
                              	tpj;	
                              (function() {			
                              	if (!/loaded|interactive|complete/.test(document.readyState)) document.addEventListener("DOMContentLoaded",onLoad); else onLoad();	
                              	function onLoad() {				
                              		if (tpj===undefined) { tpj = jQuery; if("off" == "on") tpj.noConflict();}
                              	if(tpj("#rev_slider_1_1").revolution == undefined){
                              		revslider_showDoubleJqueryError("#rev_slider_1_1");
                              	}else{
                              		revapi1 = tpj("#rev_slider_1_1").show().revolution({
                              			sliderType:"standard",
                              			jsFileLocation:"//urbango.qodeinteractive.com/wp-content/plugins/revslider/public/assets/js/",
                              			sliderLayout:"auto",
                              			dottedOverlay:"none",
                              			delay:4000,
                              			navigation: {
                              				keyboardNavigation:"off",
                              				keyboard_direction: "horizontal",
                              				mouseScrollNavigation:"off",
                               							mouseScrollReverse:"default",
                              				onHoverStop:"off",
                              				touch:{
                              					touchenabled:"on",
                              					touchOnDesktop:"off",
                              					swipe_threshold: 75,
                              					swipe_min_touches: 1,
                              					swipe_direction: "horizontal",
                              					drag_block_vertical: false
                              				}
                              				,
                              				arrows: {
                              					style:"urbango-navigation",
                              					enable:true,
                              					hide_onmobile:true,
                              					hide_under:415,
                              					hide_onleave:false,
                              					tmp:'<span class="edgtf-nav-arrow"></span>',
                              					left: {
                              						h_align:"left",
                              						v_align:"center",
                              						h_offset:20,
                              						v_offset:34
                              					},
                              					right: {
                              						h_align:"right",
                              						v_align:"center",
                              						h_offset:20,
                              						v_offset:34
                              					}
                              				}
                              			},
                              			viewPort: {
                              				enable:true,
                              				outof:"wait",
                              				visible_area:"99%",
                              				presize:false
                              			},
                              			responsiveLevels:[1920,1602,1025,480],
                              			visibilityLevels:[1920,1602,1025,480],
                              			gridwidth:[1300,1100,600,300],
                              			gridheight:[955,600,700,625],
                              			lazyType:"none",
                              			parallax: {
                              				type:"mouse",
                              				origo:"enterpoint",
                              				speed:400,
                              				speedbg:0,
                              				speedls:0,
                              				levels:[5,10,15,20,25,30,35,40,45,46,47,48,49,50,51,55],
                              				disable_onmobile:"on"
                              			},
                              			shadow:0,
                              			spinner:"spinner4",
                              			stopLoop:"off",
                              			stopAfterLoops:-1,
                              			stopAtSlide:-1,
                              			shuffle:"off",
                              			autoHeight:"off",
                              			disableProgressBar:"on",
                              			hideThumbsOnMobile:"off",
                              			hideSliderAtLimit:0,
                              			hideCaptionAtLimit:0,
                              			hideAllCaptionAtLilmit:0,
                              			debugMode:false,
                              			fallbacks: {
                              				simplifyAll:"off",
                              				nextSlideOnWindowFocus:"off",
                              				disableFocusListener:false,
                              			}
                              		});
                              	}; /* END OF revapi call */
                              	
                               }; /* END OF ON LOAD FUNCTION */
                              }()); /* END OF WRAPPING FUNCTION */
                           </script>
                           <script>
                              var htmlDivCss = '	#rev_slider_1_1_wrapper .tp-loader.spinner4 div { background-color: #FFFFFF !important; } ';
                              var htmlDiv = document.getElementById('rs-plugin-settings-inline-css');
                              if(htmlDiv) {
                              	htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss;
                              }
                              else{
                              	var htmlDiv = document.createElement('div');
                              	htmlDiv.innerHTML = '<style>' + htmlDivCss + '</style>';
                              	document.getElementsByTagName('head')[0].appendChild(htmlDiv.childNodes[0]);
                              }
                           </script>
                           <script>
                              var htmlDivCss = unescape(".urbango-navigation.tparrows%20%7B%0A%20%20%20%20background%3A%20transparent%3B%0A%20%20%20%20width%3A%2040px%3B%0A%20%20%20%20height%3A%2040px%3B%0A%7D%0A%0A.urbango-navigation.tparrows%3Abefore%20%7B%0A%09display%3A%20none%20%21important%3B%0A%7D%0A%0A.urbango-navigation.tparrows.tp-leftarrow%20.edgtf-nav-arrow%2C%20%0A.urbango-navigation.tparrows.tp-rightarrow%20.edgtf-nav-arrow%20%7B%0A%20%20%20%20position%3A%20relative%3B%0A%20%20%20%20height%3A%20100%25%3B%0A%20%20%20%20width%3A%20100%25%3B%0A%20%20%20%20display%3A%20inline-block%3B%0A%20%20%20%20vertical-align%3A%20middle%3B%0A%20%20%20%20color%3A%20%23fff%3B%0A%20%20%20%20font-size%3A%2040px%3B%0A%20%20%20%20line-height%3A%201%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%20%20-webkit-transition%3A%20color%20.3s%20ease%3B%0A%20%20%20%20transition%3A%20color%20.3s%20ease%3B%0A%7D%0A%0A.urbango-navigation.tparrows.tp-leftarrow%20.edgtf-nav-arrow%3Ahover%2C%20%0A.urbango-navigation.tparrows.tp-rightarrow%20.edgtf-nav-arrow%3Ahover%20%7B%0A%09color%3A%20%23ff3a54%3B%0A%7D%0A%0A.urbango-navigation.tparrows.tp-leftarrow%20.edgtf-nav-arrow%3Abefore%2C%20%0A.urbango-navigation.tparrows.tp-rightarrow%20.edgtf-nav-arrow%3Abefore%20%7B%0A%20%20%09display%3A%20inline-block%3B%0A%20%20%20%09vertical-align%3A%20top%3B%0A%20%20%20%09font-family%3A%20%22ElegantIcons%22%20%21important%3B%20%0A%20%20%09font-style%3A%20normal%20%21important%3B%0A%20%20%09font-weight%3A%20normal%20%21important%3B%0A%20%20%09font-variant%3A%20normal%20%21important%3B%0A%20%20%20%09text-transform%3A%20none%20%21important%3B%0A%20%20%20%09speak%3A%20none%3B%0A%20%20%20%09line-height%3A%20inherit%3B%0A%20%20%20%09-webkit-font-smoothing%3A%20antialiased%3B%0A%20%20%20%09-moz-osx-font-smoothing%3A%20grayscale%3B%0A%7D%0A.urbango-navigation.tparrows.tp-leftarrow%20.edgtf-nav-arrow%3Abefore%20%7B%0A%09content%3A%20%22%5C23%22%3B%0A%7D%0A.urbango-navigation.tparrows.tp-rightarrow%20.edgtf-nav-arrow%3Abefore%20%7B%0A%20%20%20%09%20content%3A%20%22%5C24%22%3B%0A%7D%0A");
                              var htmlDiv = document.getElementById('rs-plugin-settings-inline-css');
                              if(htmlDiv) {
                              	htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss;
                              }
                              else{
                              	var htmlDiv = document.createElement('div');
                              	htmlDiv.innerHTML = '<style>' + htmlDivCss + '</style>';
                              	document.getElementsByTagName('head')[0].appendChild(htmlDiv.childNodes[0]);
                              }
                               
                           </script>
                        </div>
                     </div>
                  </div>